# Generated by Django 4.1.7 on 2023-03-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=120, verbose_name='Enlace')),
                ('resoluciones', models.CharField(blank=True, choices=[], max_length=10, null=True, verbose_name='Resoluciones')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre')),
                ('extension', models.CharField(blank=True, max_length=120, null=True, verbose_name='Extension')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
